import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Safoo from "./Safoo";


export const metadata: Metadata = {
  title: "safwan next js work",
  description: "Generated by safwan ahmed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Link href={'../'}> <h4>HOME PAGE placed in layout.tsx file, will display on every Page</h4>  </Link>
        <Safoo/>
        {children}
        <Safoo/>
      </body>
    </html>
  );
}
